ckanext/nswdesignsystem/views.py
from __future__ import annotations

from typing import Any

from flask import Blueprint

import ckan.plugins.toolkit as tk

bp = Blueprint("nswdesignsystem", __name__)


@bp.route("/nswdesignsystem/index")
def index():
    """List of all available components/intro."""
    if not tk.h.check_access("sysadmin"):
        return tk.abort(403)

    return tk.render("nswdesignsystem/components.html")

@bp.route("/nswdesignsystem/components")
def components():
    """List of all available components/intro."""
    if not tk.h.check_access("sysadmin"):
        return tk.abort(403)

    return tk.render("nswdesignsystem/components.html")


@bp.route("/nswdesignsystem/components/<component>")
def demo(component: str):
    """Preview and code example for the component and its variants."""
    if not tk.h.check_access("sysadmin"):
        return tk.abort(403)

    data: dict[str, Any] = {
        "component": component,
        "use_iframe": False,
    }

    return tk.render("nswdesignsystem/demo.html", data)


@bp.route("/nswdesignsystem/components/<component>/embed")
def embed(component: str):
    """Standalone preview of the component."""
    if not tk.h.check_access("sysadmin"):
        return tk.abort(403)

    tpl: str = tk.h.nswdesignsystem_demo_template(component)
    data = {
        "demo_template": tpl,
    }
    return tk.render("nswdesignsystem/embed.html", data)


@bp.route("/nswdesignsystem/layouts", defaults={"layout": None})
@bp.route("/nswdesignsystem/layouts/<layout>")
def layouts(layout: str):
    """Page layout example."""
    if not tk.h.check_access("sysadmin"):
        return tk.abort(403)

    if not layout:
        return tk.render("nswdesignsystem/components.html")

    return tk.render(f"nswdesignsystem/layout/{layout}.html")


@bp.route("/nswdesignsystem/templates", defaults={"template": None})
@bp.route("/nswdesignsystem/templates/<template>")
def templates(template: str):
    """Most common page templates."""
    if not tk.h.check_access("sysadmin"):
        return tk.abort(403)

    if not template:
        return tk.render("nswdesignsystem/components.html")

    return tk.render(f"nswdesignsystem/template/{template}.html")

ckanext/nswdesignsystem/templates/components/footer.html
<footer class="nsw-footer">
    <div class="nsw-footer__upper">
        <div class="nsw-container">
            <div class="nsw-footer__group">
                <div class="nsw-footer__heading"><a href="#">Popular</a></div>
                <ul>
                    <li><a href="#">Contact the Premier</a></li>
                    <li><a href="#">Contact a Minister</a></li>
                    <li><a href="#">About NSW</a></li>
                    <li><a href="#">State flag</a></li>
                    <li><a href="#">State Funerals</a></li>
                    <li><a href="#">Buy Regional</a></li>
                    <li><a href="#">Life events</a></li>
                    <li><a href="#">NSW Government directory</a></li>
                    <li><a href="#">Service NSW locations</a></li>
                </ul>
            </div>
            <div class="nsw-footer__group">
                <div class="nsw-footer__heading"><a href="#">What's happening</a></div>
                <ul>
                    <li><a href="#">News</a></li>
                    <li><a href="#">Ministerial media releases</a></li>
                    <li><a href="#">Projects and initiatives</a></li>
                    <li><a href="#">Have your say</a></li>
                    <li><a href="#">NSW school and public holidays</a></li>
                    <li><a href="#">Find a job in NSW Government</a></li>
                    <li><a href="#">I work for NSW</a></li>
                </ul>
            </div>
            <div class="nsw-footer__group">
                <div class="nsw-footer__heading"><a href="#">Departments</a></div>
                <ul>
                    <li><a href="#">Customer Service</a></li>
                    <li><a href="#">Communities and Justice</a></li>
                    <li><a href="#">Education</a></li>
                    <li><a href="#">Health</a></li>
                    <li><a href="#">Planning, Industry and Environment</a></li>
                    <li><a href="#">Premier and Cabinet</a></li>
                    <li><a href="#">Regional NSW</a></li>
                    <li><a href="#">Transport</a></li>
                    <li><a href="#">Treasury</a></li>
                </ul>
            </div>
        </div>
        <div class="nsw-container">
            <div class="nsw-footer__group">
                <div class="nsw-footer__info">
                    <div class="nsw-footer__copyright">Copyright © 2022</div>
                </div>
            </div>
        </div>
    </div>
    <div class="nsw-footer__lower">
        <div class="nsw-container">
            <p>We pay respect to the Traditional Custodians and First Peoples of NSW, and acknowledge their continued
                connection to their country and culture.</p>
        </div>
    </div>
</footer>

ckanext/nswdesignsystem/templates/components/main_navigation.html
<nav class="nsw-skip" aria-label="Skip to links">
    <a href="#main-nav"><span>Skip to navigation</span></a>
    <a href="#"><span>Skip to content</span></a>
</nav>

{% snippet 'components/header.html', title=title %}

<nav class="nsw-main-nav" id="main-nav" aria-label="Main menu">
    <div class="nsw-main-nav__header">
        <div class="nsw-main-nav__title">Menu</div>
        <button class="nsw-icon-button js-close-nav" type="button" aria-expanded="true">
            <span class="material-icons nsw-material-icons" focusable="false" aria-hidden="true">close</span>
            <span class="sr-only">Close Menu</span>
        </button>
    </div>
    <ul class="nsw-main-nav__list">
        {% if links %}
        {{ links }}
        {% endif %}
    </ul>
</nav>

ckanext/nswdesignsystem/templates/header.html
{% ckan_extends %}


{% block header_account_profile %}
    {% block nswdesignsystem_header_demo_link %}

        {% if g.debug and current_user.sysadmin %}
            <li>
                <a href="{{ h.url_for('nswdesignsystem.index') }}" title="{{ _("NSW Design System") }}">
                    <span class="material-icons nsw-material-icons" focusable="false" aria-hidden="true">logo_dev</span>
                </a>
            </li>
        {% endif %}
    {% endblock %}

    {{ super() }}
{% endblock header_account_profile %}

ckanext/nswdesignsystem/templates/macros/_nswdesignsystem_form.html
{% from 'macros/nswdesignsystem/form/input.html' import input with context %}
{% from "macros/nswdesignsystem/form/input_block.html" import input_block with context %}
{% from 'macros/nswdesignsystem/form/checkbox.html' import checkbox with context %}
{% from 'macros/nswdesignsystem/form/select.html' import select with context %}
{% from "macros/nswdesignsystem/form/attributes.html" import attributes with context %}
{% from "macros/nswdesignsystem/form/markdown.html" import markdown with context %}
{% from "macros/nswdesignsystem/form/textarea.html" import textarea with context %}
{% from "macros/nswdesignsystem/form/prepend.html" import prepend with context %}
{% from "macros/nswdesignsystem/form/custom.html" import custom with context %}
{% from "macros/nswdesignsystem/form/errors.html" import errors with context %}
{% from "macros/nswdesignsystem/form/info.html" import info with context %}
{% from "macros/nswdesignsystem/form/hidden.html" import hidden with context %}
{% from "macros/nswdesignsystem/form/hidden_from_list.html" import hidden_from_list with context %}
{% from "macros/nswdesignsystem/form/required_message.html" import required_message with context %}
{% from "macros/nswdesignsystem/form/image_upload.html" import image_upload with context %}
{% from "macros/nswdesignsystem/form/date.html" import date with context %}
{% from "macros/nswdesignsystem/form/date_input.html" import date_input with context %}
{% from "macros/nswdesignsystem/form/global_alert.html" import global_alert with context %}

{% set input = input %}
{% set input_block = input_block %}
{% set checkbox = checkbox %}
{% set select = select %}
{% set attributes = attributes %}
{% set markdown = markdown %}
{% set textarea = textarea %}
{% set prepend = prepend %}
{% set custom = custom %}
{% set errors = errors %}
{% set info = info %}
{% set hidden = hidden %}
{% set hidden_from_list = hidden_from_list %}
{% set required_message = required_message %}
{% set image_upload = image_upload %}
{% set date = date %}
{% set date_input = date_input %}
{% set global_alert = global_alert %}

ckanext/nswdesignsystem/templates/macros/nsw_buttons.html
{% from "macros/form/attributes.html" import attributes %}

{% macro nsw_button(text='', link_class='nsw-button--light-outline-solid',icon='', attrs={}, custom_icon='', type='button') %}
<button type="{{type}}" class="nsw-button {{ link_class }} mb-sm-0 mb-3" {{ attributes(attrs) }}>
    {% if icon %}
    <span class="material-icons nsw-material-icons" focusable="false" aria-hidden="true">
        {{ icon }}
    </span>
    {% endif %}
    {% if custom_icon %}
        {{ custom_icon|safe }}
    {% endif %}
    <span>
        {{ text }}
    </span>
</button>
{% endmacro %}

ckanext/nswdesignsystem/templates/macros/nsw_links.html
{% macro blue_link(text='', route='', icon='') %}
<a href="{{ route }}" class="nsw-button nsw-button--light-outline-solid mb-sm-0 mb-3">
    {% if icon %}
    <span class="material-icons nsw-material-icons" focusable="false" aria-hidden="true">
        add
    </span>
    {% endif %}
    <span>
        {{ text }}
    </span>
</a>
{% endmacro %}

ckanext/nswdesignsystem/templates/macros/nswdesignsystem/_filter_facet.html
{% import "macros/form.html" as form %}



{% macro facet(name, values, labels=[], visible=5, title=null, sub_text='', show_all_label="Show all", empty_label=null, collapsible=false, expanded=false, attrs={}, show_all_counter=none, add_search=false) %}
    {% if not labels %}
        {% set labels = values %}
    {% endif %}

    {% call filter(collapsible and title, expanded, collapsible=collapsible, sub_text=sub_text) %}

        {% set selected = request.args.getlist(name) %}
        {% set main = values[:visible] %}
        {% set rest = values[visible:] %}

        <fieldset class="nsw-form__fieldset">
            {% if not collapsible %}
                <legend class="nsw-form__legend">
                    {{ title or name }}
                </legend>
            {% endif %}

            {% if add_search and values|length > visible %}
                {% block facet_search_input scoped %}
                    <input
                        placeholder="{{ _('Start typing to see all options') }}"
                        data-module="nsw-facet-filter"
                        type="text" class="nsw-form__input"
                        aria-label="{{ title or name }} {{ _('suggestions') }}"
                    />
                {% endblock %}
            {% endif %}

            {% for val in main %}
                {{ form.checkbox(
                    name,
                    id="filter-" ~ name ~ "-main-" ~ loop.index0, label=labels[loop.index0], value=val,
                    checked=val in selected,
                    attrs=attrs,
                )}}
            {% else %}
                {{ empty_label }}
            {% endfor %}

            {% if rest %}
                <div class="nsw-filters__all nsw-display-none">
                    {% for val in rest %}
                        {{ form.checkbox(
                            name,
                            id="filter-" ~ name ~ "-rest-" ~ loop.index0, label=labels[loop.index0 + visible], value=val,
                            checked=val in selected,
                            attrs=attrs,
                        )}}
                    {% endfor %}

                </div>
                <button class="nsw-filters__more">{{ show_all_label }} ({{ show_all_counter or values | length }})</button>

            {% endif %}

        </fieldset>
    {% endcall %}

{% endmacro %}

ckanext/nswdesignsystem/templates/macros/nswdesignsystem/_filter_filter.html
{% macro filter(button_label, expanded=false, collapsible=true, sub_text='') %}
    <div class="nsw-filters__item">

        {% if button_label and collapsible %}

            <button class="nsw-filters__item-button {{ 'active' if expanded }}" aria-expanded="{{ 'true' if expanded else 'false' }}">
                <span class="nsw-filters__item-name">{{ button_label }}</span>
                <span class="material-icons nsw-material-icons" focusable="false" aria-hidden="true">keyboard_arrow_down</span>
            </button>
        {% else %}
            {% if button_label %}
                <div class="nsw-form__legend nsw-m-bottom-sm">
                    {{ button_label }}
                </div>
            {% endif %}
        {% endif %}

        {% if sub_text %}
            <div class="nsw-form__helper">
                {{ sub_text }}
            </div>
        {% endif %}

        <div class="nsw-filters__item-content">
            {{ caller() }}
        </div>

    </div>
{% endmacro %}

ckanext/nswdesignsystem/templates/macros/nswdesignsystem/_filter_filters.html
{% macro filters(title="Filters", accept="Apply filters", cancel="Clear all filters",
    down=false, right=false, instant=false, count=false, id=null, cancel_url=null, submit_on_change=false, accept_form=none) %}
    <div class="nsw-filters{{ " js-filters" if down or right }}{{ " nsw-filters--down" if down }}{{ " nsw-filters--right" if right }}{{ " nsw-filters--instant" if instant }}" {% if id %}id="{{ id }}"{% endif %}
         {% if submit_on_change %} onchange="{{ 'document.forms["{}"]'.format(accept_form) if accept_form else 'this' }}.submit()"{% endif %}
    >

        {% if down or right %}
            <div class="nsw-filters__controls{{ "  js-filters--count" if count }}">
                <button>
                    <span class="material-icons nsw-material-icons" focusable="false" aria-hidden="true">tune</span>
                    <span>{{ title }}</span>
                    <span class="material-icons nsw-material-icons" focusable="false" aria-hidden="true">keyboard_arrow_{{ "down" if down else "right" }}</span>
                </button>
            </div>
        {% endif %}

        <div class="nsw-filters__wrapper">

            {% if right %}
                {% block close_filters_button %}
                    <div class="nsw-filters__back">
                        <button class="nsw-icon-button nsw-icon-button--flex js-close-sub-nav" type="button">
                            <span class="material-icons nsw-material-icons" focusable="false" aria-hidden="true">close</span>
                            <span class="sr-only">Close filters</span>
                        </button>
                    </div>
                {% endblock %}
            {% endif %}

            <div class="nsw-filters__title">{{ title }}</div>

            <div class="nsw-filters__list">
                {{ caller() }}
            </div>

            {% if accept %}
                <div class="nsw-filters__accept">
                    <button type="submit" class="nsw-button nsw-button--dark nsw-button--full-width"
                            {% if accept_form %} form="{{ accept_form }}"{% endif %}>
                        {{ accept }}
                    </button>
                </div>
            {% endif %}

            {% if cancel %}
                <div class="nsw-filters__cancel">
                    {% if cancel_url %}
                        <a href="{{ cancel_url }}">
                            {{ cancel }}
                        </a>
                    {% else %}
                        <button type="reset">{{ cancel }}</button>
                    {% endif %}
                </div>
            {% endif %}

        </div>
    </div>
{% endmacro %}

ckanext/nswdesignsystem/templates/macros/nswdesignsystem/_header_inner.html
{% from "macros/nswdesignsystem/_header_main.html" import main with context  %}

{% macro inner(site_title, logo_link="/") %}
    <div class="nsw-header__inner">
        <div class="nsw-header__main">
            {{ main(site_title, logo_link) }}
        </div>
        <div class="nsw-header__menu">
            <button type="button" class="js-open-nav" aria-expanded="false" aria-controls="main-nav">
                <span class="material-icons nsw-material-icons" focusable="false" aria-hidden="true">menu</span>
                <span><span class="sr-only">Open</span> Menu</span>
            </button>
        </div>

        <div class="nsw-header__search">
            <button type="button" class="js-open-search" aria-expanded="false" aria-controls="header-search">
                <span class="material-icons nsw-material-icons" focusable="false" aria-hidden="true">search</span>
                <span><span class="sr-only">Show</span> Search</span>
            </button>
        </div>
    </div>
{% endmacro %}

ckanext/nswdesignsystem/templates/macros/nswdesignsystem/_header_main.html
{% macro main(title, logo_link="/") %}
    <div class="nsw-header__waratah">
        <a href="{{ logo_link }}">
            {% include "snippets/nswdesignsystem/header_logo.html" %}
            <span class="sr-only">{{ _("NSW Government") }}</span>
        </a>
    </div>
    <div class="nsw-header__name">
        <div class="nsw-header__title">{{ title }}</div>
    </div>
{% endmacro %}

ckanext/nswdesignsystem/templates/macros/nswdesignsystem/_navigation_link.html
{% macro link(details, path) %}
    <a href="{{ details.href }}" role="button" aria-expanded="false" aria-controls="sub-nav-{{ path | join("-") }}">
        <span>{{ details.label }}</span>
        {% if details.subnav %}
            <span class="material-icons nsw-material-icons" focusable="false" aria-hidden="true">keyboard_arrow_right</span>
        {% endif %}
    </a>
{% endmacro %}

ckanext/nswdesignsystem/templates/macros/nswdesignsystem/_side_navigation_tree.html
{% from "macros/nswdesignsystem/_side_navigation_link.html" import link with context  %}

{% macro tree(links, path, active_path, include_inactive) %}
    <ul>
        {% for child in links %}
            {% set child_path = path + [loop.index0] %}
            {% set is_active = child.active or active_path[:child_path|length] == child_path %}
            {% set render_branches = is_active or include_inactive or child.open %}

            <li class="{{ "active" if is_active }}">
                {% if caller is defined %}
                    {{ caller("link", child, child_path) }}

                    {% with parent_caller = caller %}
                        {% if child.subnav and render_branches %}
                            {% call(part, details, path) tree(child.subnav.children, child_path, active_path, include_inactive)%}
                                {{ parent_caller(part, details, path) }}
                            {% endcall %}
                        {% endif %}
                    {% endwith %}

                {% else %}
                    {{ link(child, child.is_current or active_path == child_path) }}
                    {% if child.subnav and render_branches %}
                        {{ tree(child.subnav.children, child_path, active_path, include_inactive) }}
                    {% endif %}

                {% endif %}

            </li>
        {% endfor %}
    </ul>

{% endmacro %}

ckanext/nswdesignsystem/templates/macros/nswdesignsystem/accordion.html
{% from "macros/nswdesignsystem/_accordion_toggle_all.html" import toggle_all with context  %}
{% from "macros/nswdesignsystem/_accordion_wrapper.html" import wrapper with context %}
{% from "macros/nswdesignsystem/_accordion_title.html" import title with context %}
{% from "macros/nswdesignsystem/_accordion_content.html" import content with context %}


{#
Generic accordion.

Example:

{% call(idx, part) accordion(["hello", "world"]) %}

    {% if idx == 0 %}
        Hello content

    {% elif idx == 0 %}
        World content

    {% endif %}

{% endcall %}

#}
{% macro accordion(length_or_headers, with_toggle_all=false, toggle_all_labels=[], open=[]) %}
    {% if length_or_headers is iterable %}
        {% set headers = length_or_headers %}
        {% set length = headers | length %}
    {% else %}
        {% set headers = [] %}
        {% set length = length_or_headers %}
    {% endif %}

    <div class="nsw-accordion js-accordion">
        {% if with_toggle_all %}
            {{ toggle_all(*toggle_all_labels) }}
        {% endif %}

        {% for idx in range(length) %}
            {% with inner = headers[idx] if headers else caller(idx, "title") %}
                {{ title(inner, open=idx in open) }}
            {% endwith %}

            {% with inner = caller(idx, "content") %}
                {% call content() %}
                    {{ inner }}
                {% endcall %}
            {% endwith %}

        {% endfor %}
    </div>

{% endmacro %}

{% set wrapper = wrapper %}
{% set toggle_all = toggle_all %}
{% set title = title %}
{% set content = content %}

ckanext/nswdesignsystem/templates/macros/nswdesignsystem/callout.html
{% macro callout() %}
    <div class="nsw-callout">
        <div class="nsw-callout__content">
            {{ caller() }}
        </div>
    </div>
{% endmacro %}

ckanext/nswdesignsystem/templates/macros/nswdesignsystem/hero_banner.html
{#
style: dark|light|true|off-white
#}
{% macro hero_banner(title, intro, style="dark", img=none, with_lines=false) %}
    {% call wrapper(style, with_lines) %}
        {% call content() %}
            <h1>{{ title }}</h1>
            <p class="nsw-intro">{{ intro }}</p>
        {% endcall %}

        {% if img %}
            {{ image(img) }}
        {% elif with_lines %}
            {{ lines() }}
        {% endif %}

    {% endcall %}
{% endmacro %}

{% macro wrapper(style="dark", with_lines=false) %}
    <div class="nsw-hero-banner nsw-hero-banner--{{ style }} nsw-hero-banner--wide {{ 'nsw-hero-banner--lines' if with_lines }}">
        <div class="nsw-hero-banner__container">
            <div class="nsw-hero-banner__wrapper">
                {{ caller() }}
            </div>
        </div>
    </div>
{% endmacro %}

{% macro content() %}
    <div class="nsw-hero-banner__content">
        {{ caller() }}
    </div>
{% endmacro %}

<div class="nsw-hero-banner__lines"></div>
{% macro image(src) %}
    <div class="nsw-hero-banner__box">
        <img class="nsw-hero-banner__image" src="{{ src }}" alt="Banner image" />
    </div>

{% endmacro %}

{% macro lines() %}
    <div class="nsw-hero-banner__box">
        <div class="nsw-hero-banner__lines"></div>
    </div>
{% endmacro %}

{% macro links(title=none, links=[]) %}
    <div class="nsw-hero-banner__links">
        <div class="nsw-hero-banner__list">
            {% if title %}
                <div class="nsw-hero-banner__sub-title">{{ title }}</div>
            {% endif %}
            <ul>
                {% for link in links %}
                    <li><a href="{{ link.href }}">{{ link.label }}</a></li>
                {% endfor %}
            </ul>
        </div>
    </div>

{% endmacro %}

ckanext/nswdesignsystem/templates/macros/nswdesignsystem/main_navigation.html
{% from "macros/nswdesignsystem/masthead.html" import masthead with context  %}
{% from "macros/nswdesignsystem/header.html" import header with context  %}
{% from "macros/nswdesignsystem/navigation.html" import main with context  %}

{% macro main_navigation(navigation_links=null) %}
    {{ masthead() }}
    {{ header(g.site_title) }}

    {% with links = navigation_links if navigation_links is defined else h.nswdesignsystem_header_links("navigation") %}
        {{ main(links) if links }}
    {% endwith %}
{% endmacro %}

ckanext/nswdesignsystem/templates/macros/nswdesignsystem/masthead.html
{% macro masthead() %}
    <div class="nsw-masthead">
        <div class="nsw-container">
            <div class="masthead-ckan-wrapper">
                <span class="mastead-gov-static">{{ _("A NSW Government website") }}</span>
                {% if caller is defined %}
                    {{ caller() }}
                {% endif %}
            </div>
        </div>
    </div>
{% endmacro %}

ckanext/nswdesignsystem/templates/macros/nswdesignsystem/progress_indicator.html
{% macro progress_indicator(length, active, label=null) %}
    <div class="nsw-progress-indicator">
        <div class="nsw-progress-indicator__count">
            {{ label or _("Step {active} of {total}").format(active=active, total=length) }}
        </div>
        <div class="nsw-progress-indicator__bar">
            {% for step in range(length) %}
                <div{% if step < active %} class="active"{% endif %}></div>
            {% endfor %}
        </div>
    </div>
{% endmacro %}

ckanext/nswdesignsystem/templates/macros/nswdesignsystem/table.html
{% macro table(width_or_headers, height_or_rows, striped=false, bordered=false, caption=null) %}
    {% if width_or_headers is iterable %}
        {% set headers = width_or_headers %}
        {% set width = headers | length %}
    {% else %}
        {% set headers = [] %}
        {% set width = width_or_headers %}
    {% endif %}

    {% if height_or_rows is iterable %}
        {% set rows = height_or_rows %}
        {% set height = rows | length %}
    {% else %}
        {% set rows = [] %}
        {% set height = height_or_rows %}
    {% endif %}


    <div class="nsw-table{{ "  nsw-table--striped" if striped }}{{ "  nsw-table--bordered" if bordered }}" tabindex="0">
        <table>
            {% if caption %}
                <caption>{{ caption }}</caption>
            {% endif %}
            <thead>
                <tr>
                    {% for idx in range(width) %}
                        {% if headers %}
                            <th>{{ headers[idx] }}</th>
                        {% else %}
                            {{ caller(0, idx, "head_cell") }}
                        {% endif %}
                    {% endfor %}
                </tr>
            </thead>
            <tbody>
                {% for row_idx in range(height) %}
                    <tr>
                        {% for cell_idx in range(width) %}
                            {% if rows %}
                                <td>
                                    {{ rows[row_idx][cell_idx] }}
                                </td>
                            {% else %}
                                {{ caller(row_idx, cell_idx, "body_cell") }}
                            {% endif %}

                        {% endfor %}
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
{% endmacro %}

ckanext/nswdesignsystem/templates/nswdesignsystem/base.html
{% extends "page.html" %}
{% from "macros/nswdesignsystem/side_navigation.html" import side_navigation with context  %}

{% set links = h.nswdesignsystem_demo_links() %}

{% set active_path = h.nswdesignsystem_get_active_path(links, request.path) %}

{% block styles %}
    {{ super() }}
    {% asset 'nswdesignsystem/hljs-css' %}
{% endblock %}

{% block scripts %}
    {{ super() }}
    {% asset 'nswdesignsystem/hljs-js' %}
    <script>
     window.addEventListener("load", () => hljs.highlightAll())
    </script>
{% endblock %}

{% block secondary_content %}
    <div class="m-2">
        {{ side_navigation(links, active_path) }}
    </div>
{% endblock %}

{% block primary_content %}

{% endblock %}

ckanext/nswdesignsystem/templates/nswdesignsystem/components.html
{% extends "nswdesignsystem/base.html" %}

ckanext/nswdesignsystem/templates/nswdesignsystem/demo.html
{% extends "nswdesignsystem/components.html" %}
{% from "macros/nswdesignsystem/tabs.html" import tabs with context  %}

{% block primary_content %}

    <div class="p-2">
        {% for variant in h.nswdesignsystem_demo_variants(component) %}
            {% set embed_url = h.url_for("nswdesignsystem.embed", component=variant) %}

            <p class="nsw-h4">
                <a href="{{ embed_url }}" target="_blank" rel="nofollow" class="js-link">
                    <span>{{ variant.split("_") | join(" ") | capitalize }}</span>
                    <span class="material-icons nsw-material-icons" title="Open in new tab">open_in_new</span>
                </a>
            </p>

            {% call(idx) tabs(["Preview", "Code", "Details"]) %}
            {% if idx == 0 %}
                {% if use_iframe %}
                    <iframe frameborder="0" src="{{ embed_url }}" class="w-100" ></iframe>

                {% else %}
                    <section>
                        {% include h.nswdesignsystem_demo_template(variant) %}
                    </section>

                {% endif %}

            {% elif idx == 1 %}
                <pre><code class="language-django">{{ h.nswdesignsystem_demo_code(variant) }}</code></pre>

            {% elif idx == 2 %}
                {% include [h.nswdesignsystem_demo_details(variant), "nswdesignsystem/snippets/missing_demo_details.html"] %}

            {% endif %}
            {% endcall %}
            <hr/>

        {% else %}
            {% include "nswdesignsystem/snippets/missing_demo.html" %}

        {% endfor %}

    </div>
{% endblock %}

ckanext/nswdesignsystem/templates/nswdesignsystem/demo/accordion.preview.html
{% from "macros/nswdesignsystem/accordion.html" import accordion with context  %}


{% call(idx, part) accordion(["Hello", "World"]) %}
{% if idx == 0 %}
    Sed tempus, urna et pharetra pharetra, massa massa ultricies mi, quis
    hendrerit dolor magna eget est! Cursus risus, at ultrices mi tempus
    imperdiet nulla malesuada pellentesque elit eget gravida cum.

{% elif idx == 1 %}
    Quis commodo odio aenean sed adipiscing diam donec adipiscing? Praesent
    tristique magna sit amet purus gravida quis blandit turpis cursus in hac
    habitasse platea dictumst quisque sagittis, purus sit amet?

{% endif %}
{% endcall %}